import { Injectable } from '@angular/core';
import { of } from 'rxjs';
import { Program } from '../interfaces/pages.interface';

@Injectable({
  providedIn: 'root', // <- Makes it globally available
})
export class ProgramsService {
  getPrograms() {
    // Mock data - replace with real API later
    const mockPrograms: Program[] = [
      {
        id: 'google',
        name: 'Google VDP',
        logo: 'https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png',
        description: 'Report vulnerabilities in Google services',
        public: true,
        category: 'Web',
        url: 'https://bughunters.google.com',
        updatedAt: new Date('2023-10-01'),
        inScope: ['*.google.com', '*.youtube.com', 'Android apps (Play Store distribution only)'],
        outScope: ['*.blogger.com', 'Google Cloud physical infrastructure', 'Social engineering'],
        rewards: {
          critical: 15000,
          high: 8000,
          medium: 2000,
          low: 500,
        },
        policyUrl: 'https://google.com/security',
        launchDate: new Date('2020-05-01'),
      },
      {
        id: 'microsoft',
        name: 'Microsoft Bounty Program',
        logo: 'https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b',
        description: 'Earn rewards for finding security vulnerabilities in Microsoft products and services. We welcome reports across our entire ecosystem.',
        public: true,
        category: 'Cloud, OS, Software',
        url: 'https://www.microsoft.com/msrc/bounty',
        updatedAt: new Date('2023-09-15'),
        inScope: ['*.microsoft.com', '*.azure.com', 'Windows 10/11 (latest builds)', 'Microsoft 365 web applications', 'Xbox Live services'],
        outScope: ['Microsoft Store apps (unless explicitly listed)', 'Third-party integrations', 'Social engineering/phishing', 'Physical security testing', 'DDoS vulnerabilities'],
        rewards: {
          critical: 20000,
          high: 10000,
          medium: 2500,
          low: 500,
        },
        policyUrl: 'https://www.microsoft.com/msrc/bounty-terms',
        launchDate: new Date('2013-06-15'),
      },
      {
        id: 'apple',
        name: 'Apple Security Bounty',
        logo: 'https://www.apple.com/ac/structured-data/images/knowledge_graph_logo.png?20230330',
        description: 'Rewards for vulnerabilities in Apple operating systems, hardware, and services.',
        public: true,
        category: 'Mobile, OS, Hardware',
        url: 'https://developer.apple.com/security-bounty',
        updatedAt: new Date('2023-11-01'),
        inScope: ['iOS/macOS kernel vulnerabilities', 'iCloud web interfaces', 'Secure Enclave', 'Apple Pay implementation'],
        outScope: ['Third-party apps on App Store', 'Beta/Pre-release software', 'Physical device attacks'],
        rewards: {
          critical: 25000,
          high: 15000,
          medium: 5000,
          low: 1000,
        },
        policyUrl: 'https://support.apple.com/security-bounty',
        launchDate: new Date('2016-08-01'),
      },
      {
        id: 'facebook',
        name: 'Meta Bug Bounty',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Meta_Platforms_Inc._logo.svg',
        description: 'Rewards for security vulnerabilities affecting Facebook, Instagram, WhatsApp, and other Meta services.',
        public: true,
        category: 'Social Media',
        url: 'https://www.facebook.com/whitehat',
        updatedAt: new Date('2023-10-15'),
        inScope: ['facebook.com domains', 'Instagram Android/iOS apps', 'WhatsApp Web', 'Oculus Store payments'],
        outScope: ['Third-party integrations', 'Social engineering', 'Theoretical vulnerabilities'],
        rewards: {
          critical: 30000,
          high: 15000,
          medium: 3000,
          low: 500,
        },
        policyUrl: 'https://www.facebook.com/whitehat/bounty',
        launchDate: new Date('2011-07-01'),
      },
      {
        id: 'tesla',
        name: 'Tesla Vehicle Security',
        logo: 'https://www.tesla.com/themes/custom/tesla_frontend/assets/favicons/favicon-196x196.png',
        description: 'Rewards for vulnerabilities affecting Tesla vehicles and energy products.',
        public: true,
        category: 'Automotive',
        url: 'https://www.tesla.com/bugbounty',
        updatedAt: new Date('2023-09-20'),
        inScope: ['Vehicle firmware (latest versions)', 'Tesla Mobile App', 'Charging infrastructure', 'Vehicle-to-Grid systems'],
        outScope: ['Physical vehicle damage', 'Social engineering', 'Third-party charging stations'],
        rewards: {
          critical: 50000,
          high: 20000,
          medium: 5000,
          low: 1000,
        },
        policyUrl: 'https://www.tesla.com/legal/security',
        launchDate: new Date('2014-10-01'),
      },
      {
        id: 'uber',
        name: 'Uber Bug Bounty',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/5/58/Uber_logo_2018.svg',
        description: 'Rewards for security vulnerabilities in Uber apps, services, and infrastructure.',
        public: true,
        category: 'Transportation',
        url: 'https://hackerone.com/uber',
        updatedAt: new Date('2023-08-10'),
        inScope: ['uber.com domains', 'Driver/Rider apps', 'Payment processing', 'Uber Eats restaurant portal'],
        outScope: ['Uber-owned websites without sensitive data', 'Physical attacks on drivers', 'Rate limiting/DDoS'],
        rewards: {
          critical: 20000,
          high: 10000,
          medium: 3000,
          low: 500,
        },
        policyUrl: 'https://www.uber.com/legal/security',
        launchDate: new Date('2016-05-01'),
      },
      {
        id: 'coinbase',
        name: 'Coinbase Security Program',
        logo: 'https://images.ctfassets.net/q5ulk4bp65r7/3TBS4oVkD1ghowTqVQJlqj/2dfd4ea3b623a7c0d8deb2ff445dee9e/Consumer_Wordmark.svg',
        description: 'Rewards for vulnerabilities affecting Coinbase cryptocurrency exchange and wallet services.',
        public: true,
        category: 'Blockchain',
        url: 'https://hackerone.com/coinbase',
        updatedAt: new Date('2023-11-05'),
        inScope: ['coinbase.com domains', 'Mobile wallet apps', 'Coinbase Pro API', 'USD Coin (USDC) smart contracts'],
        outScope: ['Coinbase Commerce plugins', 'Social engineering', 'Blockchain protocol vulnerabilities'],
        rewards: {
          critical: 50000,
          high: 25000,
          medium: 5000,
          low: 500,
        },
        policyUrl: 'https://www.coinbase.com/security',
        launchDate: new Date('2014-03-01'),
      },
    ];

    return of(mockPrograms); // Wrap in Observable
  }
}
